### ISSUE TITLE
기술스택중 개발언어는 무엇으로?

### ISSUE THREAD

**Issue by sehan** [winning-league/league-manager#1]
+ ruby ( sinatra , rails ) 
+ node.js ( express, ... )
+ python 
+ 기타

@winning-league/developer 
의견주세요.

**Comment by ygmaster** [comment]
기존 2014리그 페이지처럼 runway에 서비스하는건가요?
루비도 runway에서 지원했었나요?

**Comment by sehan** [comment]
@ygmaster runway 가 아닌 iaas 에서 서비스 하는것으로 생각하고 있습니다.

**Comment by mayjune** [comment]
저는 node 를 강력하게 원합니다. !!! 음헤헷 ~~
근데 재밌는 건 장고가 전혀 언급되고 있지 않는 상황이네요 ㅎㅎ

**Comment by sehan** [comment]
@winning-league/developer 오늘안에 결정하는것으로 ^^

댓글로 투표해주세요.

**Comment by mayjune** [comment]
위에도 썼지만 투표를 하자면 ..

Javascript / Node.js 에 투표합니다. !!

**Comment by kjs8469** [comment]
전 뭐든 좋습니다.

**Comment by sehan** [comment]
@winning-league/developer node.js 로 갑시다. 노드 퐈이야~
