### ISSUE TITLE
match talk

### ISSUE THREAD

**Issue by sehan** [winning-league/league-manager#23]
경기댓글을 한곳에 모아 최근순으로 모든 경기댓글을 제공하여 실시간 커뮤니케이션을 유도한다.

댓글을 아래 관계를 가진다.
+ Game hasMany Comment
+ Match hasMany Comment

**Comment by sehan** [comment]
#20 경기댓글 이슈를 먼저 처리하고 match talk 를 구현한다.

**Comment by kjs8469** [comment]
대댓글도 가능한가요? ㅎ
Comment hasMany Comment? ㅎ

**Comment by sehan** [comment]
@kjs8469 일단 댓글만 ㅋ
