### ISSUE TITLE
프로젝트 탬플릿

### ISSUE THREAD

**Issue by sehan** [winning-league/league-manager#4]
+ server
 + node.js
 + expressjs ( web app framework )
 + swig ( template engine ) - http://paularmstrong.github.io/swig/
 + sequelize ( orm ) - http://sequelizejs.com
+ front
 + js - jquery, underscore
 + css - bootstrap 3
+ Database
 + SQLite - http://www.sqlite.org 

기반 프로젝트 탬플릿 작성하기
Season Model 에 대한 CRUD 를 기본구현까지

**Comment by sehan** [comment]
주말에 프로젝트에 사용할 기술사용을 위한 트래이닝 완료~

**Comment by ygmaster** [comment]
(Good)

**Comment by kjs8469** [comment]
(벌써)

**Comment by kjs8469** [comment]
기본기 습득과정좀 공유 부탁드립니다.
저도 기본기를 습득해야해서..;ㅠ

**Comment by kjs8469** [comment]
의견은 많이 있긴한데 일이 커질까봐.. 차마 말을 못하겟네요...ㅋ

**Comment by sehan** [comment]
@kjs8469 ㅋㅋ 하고 싶은 말이 있으면 일단 꺼내놓고 생각하는겁니다. 
궁금하니 말해주세요.

**Comment by kjs8469** [comment]
@sehan 프로젝트를 글로벌하게 영어로 진행하자는 얼토당토않은 이야기 하나와 ㅋ
좀 진작 말씀드렸어야 했을거같은 프로젝트 구조를~ rest api 형태로 만들어서 템플릿엔진 사용하지 않고  angularjs 같은 MVW Framework 프레임웤을 이용해서 작업하는건 어떨까 합니다~

**Comment by kobchang** [comment]
ㅋ 전에 kjs8469와 이야기 한 것 같긴한데, 개발 관련된 이야기는 아니지만,
이전 리그를 진행하면서 약간 불편하다고 생각했던것들 중에 하나가 서로 경기일정을 잡는거 였는데요.
경기일정을 잡을 때 아지트에서 이야기하면 기록이 남긴 하지만, 언제 어떤 경기를 하는지 찾아보기가 쉽지 않고, 메신져로 서로 이야기해서 경기일정을 잡고 아지트에 글을 남기지 않으면 언제 경기를 하는지 알 수가 없고, 경기일정이 겹치기도 해서 누군가가(루피?ㅋ) 교통정리를 하곤 했던거 같은데요.

해서 '경기일정설정?' 과 같은 탭을 하나 만들어서 한주에 진행되어야 할 경기리스트들을 보여주고,
자신의 경기에 가능한 날짜/시간들을 정해서 상대방에게 카톡이라든지 메신져로 보내면 상대방도 가능한 날짜/시간을 선택해서 경기일정이 정해지면 그주의 모든 경기를 언제 몇시에 하는지 쉽게 볼 수도 있고, 경기일정을 잡기위한 커뮤니케이션 비용도 좀 줄일 수 있을 것 같은데요.ㅋ
이미 기획자님?이 생각하신 개선안이 많아서 회의때는 말씀 안드렸지만, 언젠가는 적용하면 좋을것 같은데 어떠신지  의견 부탁드릴께요 ㅋ

**Comment by kjs8469** [comment]
@kobchang 좋습니다~
캘린더같은게 있음 좋겟네요~

**Comment by sehan** [comment]
@kobchang 중요도가 아주 놓은 이슈네요.
경기일정
+ 경기일정 등록
+ 경기일정 목록(혹은 캘린더)

추가로 알림을 카톡으로 쏴주는 것도 좋겠네요.
알림
+ 경기일정 등록시 
+ 경기결과 입력시

@winning-league/developer

**Comment by sehan** [comment]
@kjs8469 angularjs 를 써보지는 않았지만 서버데이터 처리구조를 rest api 형태로 data 만 내려주는 구조로 만들고 client template 엔진을 사용하면 page 네이게이션만 server template 을 사용하는 형태로도 구성가능합니다.

**Comment by mayjune** [comment]
와 .. 이 프로젝트 진짜 제대로다 .. ;;;
