### ISSUE TITLE
팀수가 홀수일 때 matches/schedule 이 정상적으로 만들어지지 않는 문제

### ISSUE THREAD

**Issue by mayjune** [winning-league/league-manager#43]
진짜 2층리그의 경우 총 5팀으로 구성되어 있다.
아래 그림과 같이 매칭 스케쥴이 정상적으로 만들어지지 않고 있다.

![2015-03-16 12 52 32](https://cloud.githubusercontent.com/assets/7042645/6660399/7bbeadee-cbdb-11e4-8968-7f87b607c562.png)

**Comment by sehan** [comment]
역시 날카로와요. :)
아무도 모르게 업데이트 해놓으려고 했는데.. 방심했다. ㅡ.ㅡ 에잇   @mayjune
