### ISSUE TITLE
경기일정 등록

### ISSUE THREAD

**Issue by sehan** [winning-league/league-manager#5]
경기별로 일정을 등록할 수 있도록 한다. 
경기일정이 등록되면 카톡으로 일정등록을 알려준다.

등록된 일정은 모아서 전체일정을 확인할수 있도록 전체일정 페이지도 제공한다.

- [x] 경기일정등록

**Comment by sehan** [comment]
경기일정을 등록하기 기능이 생기면 player 들이 잘 등록을 할까?
등록하는 액션자체가 귀찮아서 등록하지 않을거 같은 우려가 든다.

@winning-league/developer 의 생각은 어떤가요?

**Comment by kjs8469** [comment]
어떤 방식으로 **쌍방의 합의를 이끌어내어 편하게 등록**을 하느냐가 관건일듯 합니다.ㅎ
등록이 귀찮더라도 등록이 되고나면 알림을 주기 때문에 유용할거같긴해요~

**Comment by sehan** [comment]
경기일정등록 resolved

**Comment by sehan** [comment]
경기일정알림과 경기일정모아보기는 별도의 이슈로 생성해서 진행한다.
